/*************************************************************************
 *
 * fsc_core.h
 * Fan Speed Control related interface/functions
 *
 ************************************************************************/
#ifndef FSC_CORE_H
#define FSC_CORE_H

#include "Types.h"
#include "fsc.h"
#include "fsc_parser.h"

// FAN control algorithm
#define FSC_CTL_INVALID         0
#define FSC_CTL_PID             1
#define FSC_CTL_LINEAR          2

// Ladder can supoort max 20 steps
#define MAX_FAN_CONTROL_STEPS   20

// Liner
#define FSC_LINEAR_HEAD          0
#define FSC_LINEAR_TAIL          1
#define FSC_LINEAR_MAXPOINT      2

// Filter dirty data from FSC level
#define TEMP_READING_RANGE          10


// Sensor Scan
#define SENSOR_SCAN_DISABLE         0
#define SENSOR_SCAN_ENABLE          1


typedef struct
{
    float Pvalue;
    float Ivalue;
    float Dvalue;    
    signed char SetPoint;
    signed char SetPointType;
} PACKED FSCPID;

typedef struct
{
    INT8U TempMin;
	INT8U TempMax;
	INT8U PwmMin;
	INT8U PwmMax;
	INT8U FallingHyst;
} PACKED FSCLinear;

typedef struct
{
    INT8U  SensorNumber;            // Sensor number
    INT16S CurrentTemp;
    float  LastPWM;                 // Last PWM generated by this location
    INT16S LastTemp;                // Last max temp of this location
    INT16S LastLastTemp;
    INT8U  Present;                 // Indicate whether current sensor is present or not
                                    // 0 = absent
                                    // 1 = present
    INT8U  MinPWM;
    INT8U  MaxPWM;
    char  Label[32];
    INT8U  Algorithm;
    INT8U  CurrentPWM;
    union fscparam_t{
        FSCPID pidparam;
        FSCLinear linearparam;
    }fscparam;

} PACKED FSCTempSensor;

extern FSCTempSensor pFSCTempSensorInfo[FSC_SENSOR_CNT_MAX];

extern int FSCGetPWMValue( INT8U *PWMValue, FSCTempSensor *pFSCTempSensorInfo, INT8U verbose, int BMCInst );


#endif // FSC_CORE_H

